import 'dart:math';

import 'package:flutter/material.dart';

class GameScreen extends StatefulWidget {
  final int time;
  const GameScreen({
    Key? key,
    required this.time,
  }) : super(key: key);

  @override
  _GameScreenState createState() => _GameScreenState();
}

class _GameScreenState extends State<GameScreen> {
  @override
  Widget build(BuildContext context) {
    List<dynamic> emojis = [
      "🎈",
      "🧨",
      "✨",
      "🎉",
      "🎊",
      "🎃",
      "🎄",
      "🎍",
      "🎏",
      "🎐",
      "🎑",
      "🧧",
      "🎀",
      "🎁",
      "🎗️",
      "🎞️",
      "🎫",
      "🎪",
      "🎭",
      "🖼️",
      "🎨",
      "🧵",
      "🧶",
      "🥇",
      "🎖️",
      "🏆",
      "🎮",
      "🧩",
      "🪄",
      "🔮",
      "🎲",
      "♣️",
      "♠️",
      "♥️",
      "♦️",
      "🎵",
      "🎤",
      "🎧",
      "🔨",
      "⛏️",
      "🗝️",
      "🧬",
      "🔭",
      "⚖️",
      "💿",
      "🖥️",
      "🔋",
      "🗿",
      "🍕",
      "🍔",
      "🍟",
      "🌭",
      "🍿",
      "🥐",
      "🥨",
      "🍖",
      "🍗",
      "🍘",
      "🍥",
      "🍣",
      "🍩",
      "🍪",
      "🧁",
      "🍺",
      "🍾",
      "☕",
      "🍽️",
      "🍉",
      "🍊",
      "🍋",
      "🍌",
      "🍍",
      "🥭",
      "🍎",
      "🍐",
      "🍑",
      "🍄",
      "🥒",
      "🌹",
      "🌺",
      "🌻",
      "🌷",
      "🥀",
      "☘️",
      "🌳",
      "🍁",
      "🍃",
      "🍂",
      "🍀",
      "🛹",
      "✈️",
      "🚀",
      "🛸",
      "⚓",
      "🌎",
      "🪐",
      "🏔️",
      "🌧️",
      "🌤️",
      "🌩️",
      "🌕",
      "🌑",
      "🌖",
      "🌒",
      "🌓",
      "🌔",
      "🌗",
      "☀️",
      "🌜",
      "🌛",
      "🌠",
      "🌈",
      "⚡",
      "❄️",
      "🔥",
      "💧",
      "💞",
      "💕",
      "💔",
      "💫",
      "💦",
      "💤",
      "⛔",
      "🆘",
      "☢️",
      "☣️",
      "💯",
      "🐸",
      "🐹",
      "🦊",
      "🦝",
      "🐰",
      "🐻",
      "🐮",
      "🐷",
      "🐨",
      "🐗",
      "🐭",
      "🐼",
      "🐲",
      "🐔",
      "🦄",
      "🐴",
      "🐶",
      "🐺",
      "🐱",
      "🦁",
      "🐯",
      "👾",
      "👽",
      "👻",
      "💩",
      "🤖",
      "☠️",
      "👺",
    ];
    Random random = Random();
    int i = random.nextInt(emojis.length);
    int j = random.nextInt(emojis.length);
    int k = random.nextInt(emojis.length);
    while (i == k || i == j || j == k) {
      if (i == k) i = random.nextInt(emojis.length);
      if (i == j) j = random.nextInt(emojis.length);
      if (j == k) k = random.nextInt(emojis.length);
    }
    return Scaffold(
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(15),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              Column(
                children: const [
                  Text(
                    "Draw as fast as you can!",
                    style: TextStyle(fontSize: 35),
                  ),
                  SizedBox(
                    height: 5,
                  ),
                  Text(
                    "Something funny or creative related to this Emoji!",
                    style: TextStyle(fontSize: 25),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
              Text(
                "${emojis[i]}${emojis[j]}${emojis[k]}",
                style: const TextStyle(fontSize: 80),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
